/// <reference types="node" />
import esbuild from "esbuild";
import type { BuildOptions, Plugin } from "esbuild";
import process from "process";
import path from "path";
import fs from "fs/promises";
import * as v from "valibot";
import json5 from "json5";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit https://github.com/superle3/snippet-leaf
*/
`;
const version = JSON.parse(await fs.readFile("package.json", "utf-8")).version;

const production = process.argv[2] === "production";
const web = process.argv[2] === "web" || process.argv.length === 2;
const codemirror = process.argv[2] === "codemirror";
const userscript = process.argv[2] === "userscript";
type InlinePluginOptions = {
    filter: RegExp;
    namespace: string;
    transform?: (contents: string, args: any) => string | Promise<string>;
};

const getFilePath = async (
    inputPath: string,
    resolveDir: string,
    filter: string | RegExp,
) => {
    let filePath;
    if (!/^\.\.?\//.test(inputPath)) {
        filePath = path.resolve(resolveDir, inputPath);
    } else {
        filePath = inputPath;
    }
    try {
        await fs.access(filePath);
    } catch {
        const filtered_path = inputPath.replace(filter, "");
        if (/^\.\.?\//.test(filtered_path)) {
            filePath = path.resolve(resolveDir, filtered_path);
        } else {
            filePath = filtered_path;
        }
    }
    return filePath;
};
const inlin_plugin = (options?: InlinePluginOptions): Plugin => {
    const { filter, namespace, transform } = Object.assign(
        {
            /**
             *  A regex filter to match the desired import. Defaults to
             * imports that start with `inline:`, e.g. import
             * 'inline:./file.ext';
             */
            filter: /^inline:/,

            /**
             * The namespace to use. If you use more than one instance of
             * this plugin, each one should have a unique namespace. This is
             * a random string by default, so you won't need to change it
             * unless you're targeting a specific namespace.
             */
            namespace: "_" + Math.random().toString(36).substr(2, 9),

            /**
             * A function to transform the contents of the imported file.
             * This can be a simple string replace or a more complex
             * operation, such as a call to PostCSS, Sass, etc. The function
             * must return a string.
             *
             * The contents argument will be a string containing the file's
             * contents. The args argument is passed through from esbuild,
             * but the most useful is probably args.path which references
             * the file path.
             *
             * Note that heavy operations here can impact esbuild's
             * performance!
             */
            transform: async (
                contents: string,
                args: { path: string; [key: string]: any },
            ) => contents,
        },
        options,
    );

    return {
        name: "esbuild-inline-plugin",
        setup(build) {
            let alias = Object.entries(build.initialOptions.alias ?? {});
            build.onResolve({ filter }, async (args) => {
                let inputPath = alias.reduce((path, [key, val]) => {
                    return path.replace(key, val);
                }, args.path);
                const filePath = await getFilePath(
                    inputPath,
                    args.resolveDir,
                    filter,
                );

                return {
                    path: filePath,
                    namespace,
                };
            });

            build.onLoad({ filter: /.*/, namespace }, async (args) => {
                let contents = await fs.readFile(args.path, "utf8");

                if (typeof transform === "function") {
                    contents = await transform(contents, args);
                }

                return {
                    contents,
                    watchFiles: [args.path],
                    loader: "text",
                };
            });
        },
    };
};

export const json5Plugin = (): Plugin => ({
    name: "json5",
    setup(build) {
        // resolve .json5 files
        build.onResolve({ filter: /\.json5$/ }, async (args) => {
            if (args.resolveDir === "") return;
            const filePath = await getFilePath(args.path, args.resolveDir, "");
            return {
                path: filePath,
                namespace: "json5",
            };
        });

        // load files with "json5" namespace
        build.onLoad({ filter: /.*/, namespace: "json5" }, async (args) => {
            const json5Content = await fs.readFile(args.path);
            const parsed = json5.parse(json5Content.toString());

            return {
                contents: JSON.stringify(parsed),
                loader: "json",
            };
        });
    },
});

const setCodeMirrorPath = path.resolve("src/set_codemirror_objects.ts");

const codemirrorReroutePlugin: Plugin = {
    name: "codemirror-reroute",
    setup(build) {
        build.onResolve({ filter: /^@codemirror\// }, async (args) => {
            // only reroute if importer is inside src/*
            if (
                !args.importer ||
                !args.importer.startsWith(path.resolve("src") + path.sep)
            ) {
                return null; // normal resolution for non-src or entry imports
            }

            // avoid chasing self-import loops
            if (path.resolve(args.importer) === setCodeMirrorPath) {
                return {
                    errors: [
                        {
                            text: `set_codemirror_objects.ts cannot import @codemirror/*; circular dependency detected in ${args.importer}`,
                        },
                    ],
                };
            }

            try {
                await fs.access(setCodeMirrorPath);
            } catch {
                return {
                    errors: [
                        {
                            text: `set_codemirror_objects.ts not found at ${setCodeMirrorPath}; cannot reroute ${args.path}`,
                        },
                    ],
                };
            }

            return {
                path: setCodeMirrorPath,
                // namespace: "codemirror-reroute",
            };
        });

        // build.onLoad(
        //     { filter: /.*/, namespace: "codemirror-reroute" },
        //     async (...args) => {
        //         const contents = await fs.readFile(setCodeMirrorPath, "utf8");
        //         return { contents, loader: "ts" };
        //     },
        // );
    },
};

const sharedConfig: BuildOptions = {
    banner: {
        js: banner,
    },
    bundle: true,
    platform: "browser",
    target: ["ES2017"],
    sourcemap: production ? false : "inline",
    minify: production,
    plugins: [inlin_plugin(), codemirrorReroutePlugin, json5Plugin()],
    logLevel: "info",
};

const browserConfig: BuildOptions = {
    ...sharedConfig,
    entryPoints: [
        "browser_extension/browser_extension.ts",
        "browser_extension/settings/settings_tab.ts",
        "browser_extension/settings/content_script.ts",
    ],
    format: "iife",
    outdir: "browser_extension/dist",
    external: ["path", "fs"],
    metafile: true,
    mainFields: ["module", "browser", "main"],
    sourcemap: production ? false : "inline",
};

const codemirrorConfig: BuildOptions = {
    ...sharedConfig,
    entryPoints: ["codemirror_extension/codemirror_extensions.ts"],
    format: "esm",
    outdir: "codemirror_extension/dist",
};

const userscriptBanner = (
    version: string,
    require_version: string,
) => `// ==UserScript==
// @name         SnippetLeaf - LaTeX Snippets for Overleaf
// @namespace    https://github.com/superle3/snippet-leaf
// @version      ${version}
// @description  LaTeX snippet expansion for Overleaf with auto-fractions, matrix shortcuts, and more
// @author       superle3
// @match        https://www.overleaf.com/project/*
// @grant        none
// @require      https://github.com/superle3/snippet-leaf/releases/download/v${require_version}/settings_bundle-${require_version}.user.js
// @run-at       document-start
// ==/UserScript==
`;

const userscriptSettingsBanner = (version: string) => `// ==UserScript==
// @name         SnippetLeaf Settings Bundle
// @namespace    https://github.com/superle3/snippet-leaf
// @version      ${version}
// @description  Settings bundle for SnippetLeaf userscript
// @author       superle3
// @match        https://www.overleaf.com/project/*
// @grant        none
// @run-at       document-start
// ==/UserScript==
`;

const userscriptConfig = (version: string, require_version: string) =>
    ({
        ...sharedConfig,
        entryPoints: [
            {
                in: "browser_extension/browser_extension.ts",
                out: `snippetleaf-${version}`,
            },
        ],
        format: "cjs",
        outdir: "greasemonkey/dist",
        outExtension: { ".js": ".user.js" },
        banner: {
            js: userscriptBanner(version, require_version),
        },
        external: ["path", "fs"],
        mainFields: ["module", "browser", "main"],
        target: ["ES2024"],
        treeShaking: true,
        minify: true,
        sourcemap: false,
    }) satisfies BuildOptions;
const userscriptSettingsBundleConfigs = (version: string) =>
    ({
        ...userscriptConfig(version, version),
        banner: {
            js: userscriptSettingsBanner(version),
        },
        entryPoints: [
            {
                in: "greasemonkey/settings_bundle.ts",
                out: `settings_bundle-${version}`,
            },
        ],
        format: "cjs",
        minify: false,
        sourcemap: false,
        legalComments: "none",
    }) as const satisfies BuildOptions;

if (web) {
    const browserCtx = await esbuild.context(browserConfig);
    browserCtx.watch().catch(() => process.exit(1));
} else if (codemirror) {
    console.log("Running in development mode, watching for changes...");
    const codemirrorCtx = await esbuild.context(codemirrorConfig);
    codemirrorCtx.watch().catch(() => process.exit(1));
} else if (userscript) {
    userScriptBuild(version);
    // console.log("Building Greasemonkey userscript...");
    // await esbuild.build(userscriptSettingsBundleConfigs(version));
    // console.log("Fetching latest settings")

    await esbuild.build(userscriptConfig);
} else if (production) {
    console.log("Building for production...");
    await esbuild.build(browserConfig);
}

const ReleaseSchema = v.object({
    assets: v.array(
        v.object({
            browser_download_url: v.string(),
            name: v.string(),
        }),
    ),
});

function stripUserScript(source: string) {
    return source
        .replace(/^\/\/ ==UserScript==.*\/\/ ==\/UserScript==/s, "")
        .trim();
}
async function userScriptBuild(version: string) {
    console.log("Building Greasemonkey userscript...");
    const temp_user_script_settings_bundle =
        userscriptSettingsBundleConfigs(version);
    await esbuild.build(temp_user_script_settings_bundle);
    console.log("fetching url");
    const latest_release_url =
        "https://api.github.com/repos/superle3/snippet-leaf/releases/latest";
    const response = await fetch(latest_release_url);
    const json = (await response.json()) as unknown;
    const release_url = v.parse(ReleaseSchema, json);
    const old_settings_bundle_asset = release_url.assets
        .map((asset) => {
            const name = asset.name.match(
                /settings_bundle-(?<major>\d+)\.(?<minor>\d+)\.(?<patch>\d+)\.user\.js/,
            );
            if (name === null) return name;
            return { name, url: asset.browser_download_url };
        })
        .filter((asset) => asset !== null)?.[0];
    let settings_bundle_version = version;
    if (old_settings_bundle_asset) {
        const { major, minor, patch } = old_settings_bundle_asset.name
            .groups as { major: string; minor: string; patch: string };
        const old_settings_bundle_response = await fetch(
            old_settings_bundle_asset.url,
        );
        const old_settings_bundle = await old_settings_bundle_response.text();
        const new_file = await fs.readFile(
            `greasemonkey/dist/settings_bundle-${version}.user.js`,
        );
        if (
            stripUserScript(old_settings_bundle) ===
            stripUserScript(new_file.toString())
        ) {
            console.log(
                "Nothing changed in settings bundle, keeping the old version",
            );
            settings_bundle_version = `${major}.${minor}.${patch}`;
        }
    }
    console.log(
        `Building Settings Bundle again for version settings: ${settings_bundle_version} extension ${version}`,
    );
    const new_config = userscriptSettingsBundleConfigs(settings_bundle_version);
    await esbuild.build(new_config);
    console.log(
        "Building codemirror extension",
        version,
        settings_bundle_version,
    );
    await esbuild.build(userscriptConfig(version, settings_bundle_version));
}
