import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import inlineImportPlugin from "esbuild-plugin-inline-import";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");
const args = {
	banner: {
		js: banner,
	},
	entryPoints: [
        "src/extension.ts"
	],
	bundle: true,
	format: "iife", // or "esm" if your manifest supports it
	platform: "browser",
	target: ["es2017"], // or "es2017"
	outdir: "dist",
	sourcemap: prod ? false : "inline",
	plugins: [
		inlineImportPlugin()
	],
	logLevel: "info"
};

if (!prod) {
	const ctx = await esbuild.context(args);
	ctx.watch().catch(() => process.exit(1));
}
else {
	esbuild.build(args).catch(() => process.exit(1));
}
